services:
  artifact:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/workspace/segfold/output
    deploy:
      resources:
        limits:
          memory: 64g
    stdin_open: true
    tty: true
