#!/usr/bin/env python3
"""
Animator script for C++ generated trace files.
This script uses the existing Python animator to visualize traces generated by the C++ simulator.
"""

import sys
import os
import json
import argparse

# Add parent directory to path to import segfold modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '../../..'))

from segfold.animator.animator import GridTraceAnimator, HierGridTraceAnimator

def main():
    parser = argparse.ArgumentParser(description='Animate trace files generated by C++ simulator')
    parser.add_argument('trace_file', type=str, help='Path to trace JSON file')
    parser.add_argument('--output', '-o', type=str, default='animation.gif',
                       help='Output animation file (default: animation.gif)')
    parser.add_argument('--rows', '-M', type=int, default=None,
                       help='Number of PE rows (auto-detected from trace if not provided)')
    parser.add_argument('--cols', '-N', type=int, default=None,
                       help='Number of PE columns (auto-detected from trace if not provided)')
    parser.add_argument('--format', '-f', type=str, choices=['gif', 'mpeg'], default='gif',
                       help='Output format (default: gif)')
    parser.add_argument('--fps', type=int, default=4,
                       help='Frames per second (default: 4)')
    parser.add_argument('--interval', type=int, default=500,
                       help='Animation interval in milliseconds (default: 500)')
    parser.add_argument('--start-cycle', type=int, default=0,
                       help='Start cycle (default: 0)')
    parser.add_argument('--end-cycle', type=int, default=None,
                       help='End cycle (default: None, animates all)')
    parser.add_argument('--hierarchical', action='store_true',
                       help='Use hierarchical animator (includes FIFOs)')
    parser.add_argument('--repeat', action='store_true',
                       help='Repeat animation')

    args = parser.parse_args()

    if not os.path.exists(args.trace_file):
        print(f"Error: Trace file not found: {args.trace_file}", file=sys.stderr)
        sys.exit(1)

    # Read PE dimensions from trace file if not provided
    rows = args.rows
    cols = args.cols
    if rows is None or cols is None:
        with open(args.trace_file, 'r') as f:
            trace_data = json.load(f)
        if rows is None:
            rows = trace_data.get('pe_rows')
            if rows is None:
                print("Error: PE rows not found in trace file and -M not provided", file=sys.stderr)
                sys.exit(1)
        if cols is None:
            cols = trace_data.get('pe_cols')
            if cols is None:
                print("Error: PE cols not found in trace file and -N not provided", file=sys.stderr)
                sys.exit(1)
        print(f"Auto-detected PE grid: {rows}x{cols}")

    # Create animator
    if args.hierarchical:
        animator = HierGridTraceAnimator(rows, cols)
    else:
        animator = GridTraceAnimator(rows, cols)
    
    # Animate
    try:
        animator.animate(
            trace_file=args.trace_file,
            out_file=args.output,
            interval=args.interval,
            fps=args.fps,
            repeat=args.repeat,
            fmt=args.format,
            start_cycle=args.start_cycle,
            end_cycle=args.end_cycle
        )
        print(f"Animation saved to {args.output}")
    except Exception as e:
        print(f"Error creating animation: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()



