Frontend:
  impl: GEM5
  clock_ratio: 1

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: HBM2
    org:
      preset: HBM2_8Gb
    timing:
      preset: HBM2_2Gbps

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy

  AddrMapper:
    impl: RoBaRaCoCh
