#!/usr/bin/env python3
"""Shape Sensitivity: sweep synthetic K x K square matrix density and operand role.

For each real nonsquare matrix A_real (M x K), and each (density, seed) of a
uniform-sparse K x K matrix S, runs the simulator in two operand-role
configurations:

  Direction 1 (forward)  : A_real (M x K) x S       (K x K)
  Direction 2 (transpose):       S       (K x K) x A_real^T (K x M)

Same S is reused across both directions per (K, density, seed). No baselines.
Reports raw cycles per (matrix, density, seed, direction) tuple.

Inputs must be pre-generated by scripts/gen_shape_sensitivity_inputs.py.

Usage:
    python3 scripts/run_shape_sensitivity.py output/shape_sens_<ts>
    python3 scripts/run_shape_sensitivity.py output/shape_sens_<ts> --jobs 4 \
        --matrices Franz6 --densities 0.0005 --directions both
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Mirror of run_nonsquare.py:25-32.
MATRIX_DIMS = {
    "lp_woodw": (1098, 8418),
    "pcb3000":  (3960, 7732),
    "gemat1":   (4929, 10595),
    "Franz6":   (7576, 3016),
    "Franz8":   (16728, 7176),
    "psse1":    (14318, 11028),
}

DEFAULT_DENSITIES = [0.0005, 0.001, 0.002, 0.004, 0.008, 0.016, 0.032]
DEFAULT_SEEDS = [42]
DEFAULT_DIRECTIONS = (1, 2)

CYCLE_RE = re.compile(r"completed successfully in (\d+) cycles")


def find_latest_stats(tmp_dir: Path) -> Path | None:
    files = sorted(tmp_dir.glob("run_*_stats.json"), key=os.path.getmtime, reverse=True)
    return files[0] if files else None


def synth_path(synth_dir: Path, K: int, density: float, seed: int) -> Path:
    return synth_dir / f"K{K}_d{density:.6f}_s{seed}.mtx"


def transpose_path(matrix_dir: Path, matrix: str) -> Path:
    return matrix_dir / matrix / f"{matrix}_T.mtx"


def real_path(matrix_dir: Path, matrix: str) -> Path:
    return matrix_dir / matrix / f"{matrix}.mtx"


def run_one(binary: Path, config: Path, matrix: str, density: float, seed: int,
            direction: int, a_path: Path, b_path: Path,
            out_dir: Path, tmp_root: Path, timeout: int) -> tuple:
    key = f"{matrix}_d{density:.6f}_s{seed}_dir{direction}"
    mat_tmp_dir = tmp_root / key
    mat_tmp_dir.mkdir(parents=True, exist_ok=True)

    cmd = [
        str(binary),
        "--config", str(config),
        "--mtx-file", str(a_path),
        "--mtx-file-b", str(b_path),
        "--tmp-dir", str(mat_tmp_dir),
    ]
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout,
            cwd=str(PROJECT_ROOT),
        )
        m = CYCLE_RE.search(result.stdout)
        cycles = int(m.group(1)) if m else -1

        if result.returncode != 0:
            print(f"  [FAIL] {key}: returncode={result.returncode}")
            if result.stderr:
                tail = result.stderr.strip().split("\n")[-1][:200]
                print(f"         {tail}")
            return (key, -1, False)

        latest = find_latest_stats(mat_tmp_dir)
        if latest:
            dest_name = f"sim_{matrix}_d{density:.6f}_s{seed}_stats.json"
            dest = out_dir / dest_name
            shutil.move(str(latest), str(dest))
            cfg_src = latest.with_name(latest.name.replace("_stats.json", "_config.json"))
            if cfg_src.exists():
                shutil.move(str(cfg_src), str(out_dir / dest_name.replace("_stats.json", "_config.json")))

        print(f"  [OK]   {key}: {cycles} cycles")
        return (key, cycles, True)
    except subprocess.TimeoutExpired:
        print(f"  [TIMEOUT] {key}")
        return (key, -1, False)
    except Exception as e:
        print(f"  [ERROR] {key}: {e}")
        return (key, -1, False)


def parse_directions(arg: str) -> tuple:
    if arg == "both":
        return (1, 2)
    if arg in ("1", "2"):
        return (int(arg),)
    raise argparse.ArgumentTypeError(f"--directions must be 1, 2, or both (got {arg!r})")


def build_tasks(args, synth_dir: Path, matrix_dir: Path):
    """Build the list of (matrix, density, seed, direction, a_path, b_path) tuples and
    return alongside any missing-input errors."""
    tasks = []
    missing = []
    for matrix in args.matrices:
        M, K = MATRIX_DIMS[matrix]
        a_real = real_path(matrix_dir, matrix)
        a_real_t = transpose_path(matrix_dir, matrix)
        for density in args.densities:
            for seed in args.seeds:
                s_path = synth_path(synth_dir, K, density, seed)
                for direction in args.directions:
                    if direction == 1:
                        a_path, b_path = a_real, s_path
                    else:
                        a_path, b_path = s_path, a_real_t
                    for p in (a_path, b_path):
                        if not p.exists():
                            missing.append(p)
                    tasks.append((matrix, density, seed, direction, a_path, b_path))
    return tasks, sorted(set(missing))


def main():
    parser = argparse.ArgumentParser(description="Shape sensitivity sweep")
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--jobs", type=int, default=4)
    parser.add_argument("--config", type=Path,
                        default=PROJECT_ROOT / "configs" / "segfold-dtonly.yaml")
    parser.add_argument("--matrices", nargs="+", default=list(MATRIX_DIMS.keys()))
    parser.add_argument("--densities", nargs="+", type=float, default=DEFAULT_DENSITIES)
    parser.add_argument("--seeds", nargs="+", type=int, default=DEFAULT_SEEDS)
    parser.add_argument("--directions", type=parse_directions, default=DEFAULT_DIRECTIONS,
                        help="1, 2, or both (default: both)")
    parser.add_argument("--matrix-dir", type=Path,
                        default=PROJECT_ROOT / "benchmarks" / "data" / "suitesparse")
    parser.add_argument("--synth-dir", type=Path,
                        default=PROJECT_ROOT / "benchmarks" / "data" / "synthetic_square")
    parser.add_argument("--timeout", type=int, default=7200)
    args = parser.parse_args()

    unknown = [m for m in args.matrices if m not in MATRIX_DIMS]
    if unknown:
        print(f"Error: unknown matrices: {unknown}", file=sys.stderr)
        sys.exit(1)

    binary = PROJECT_ROOT / "csegfold" / "build" / "csegfold"
    if not binary.exists():
        print(f"Error: {binary} not found. Run scripts/setup.sh first.", file=sys.stderr)
        sys.exit(1)

    if not args.config.exists():
        print(f"Error: config not found: {args.config}", file=sys.stderr)
        sys.exit(1)

    config_name = args.config.stem  # e.g. "segfold-dtonly"
    out_root = args.output_dir / "shape_sensitivity" / config_name
    tmp_root = PROJECT_ROOT / "csegfold" / "tmp" / "shape_sensitivity" / config_name
    tmp_root.mkdir(parents=True, exist_ok=True)
    for direction in args.directions:
        (out_root / f"dir{direction}").mkdir(parents=True, exist_ok=True)

    tasks, missing = build_tasks(args, args.synth_dir, args.matrix_dir)
    if missing:
        print("Error: missing input MTX files. Run:", file=sys.stderr)
        print("  python3 scripts/gen_shape_sensitivity_inputs.py", file=sys.stderr)
        for p in missing[:10]:
            print(f"  missing: {p}", file=sys.stderr)
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more", file=sys.stderr)
        sys.exit(1)

    print("=" * 60)
    print("Shape Sensitivity Experiment")
    print(f"  matrices  : {args.matrices}")
    print(f"  densities : {args.densities}")
    print(f"  seeds     : {args.seeds}")
    print(f"  directions: {args.directions}")
    print(f"  config    : {args.config}")
    print(f"  output    : {out_root}")
    print(f"  total runs: {len(tasks)}")
    print("=" * 60)

    results = {}

    def submit(task):
        matrix, density, seed, direction, a_path, b_path = task
        dir_out = out_root / f"dir{direction}"
        return run_one(binary, args.config, matrix, density, seed, direction,
                       a_path, b_path, dir_out, tmp_root, args.timeout)

    if args.jobs <= 1:
        for i, task in enumerate(tasks):
            print(f"[{i+1}/{len(tasks)}]", end=" ")
            key, cycles, _ = submit(task)
            results[key] = cycles
    else:
        futures = {}
        with ThreadPoolExecutor(max_workers=args.jobs) as ex:
            for task in tasks:
                futures[ex.submit(submit, task)] = task
            for fut in as_completed(futures):
                key, cycles, _ = fut.result()
                results[key] = cycles

    print()
    print("=" * 60)
    print("Summary")
    print("=" * 60)
    ok = sum(1 for c in results.values() if c > 0)
    print(f"  Succeeded: {ok}/{len(tasks)}")
    for matrix in args.matrices:
        for density in args.densities:
            for seed in args.seeds:
                for direction in args.directions:
                    key = f"{matrix}_d{density:.6f}_s{seed}_dir{direction}"
                    c = results.get(key, -1)
                    status = f"{c:>10} cycles" if c > 0 else "     FAILED"
                    print(f"    {key:60s} {status}")


if __name__ == "__main__":
    main()
